#!/bin/bash

# Function to check if a file is a header file
is_header_file() {
	    local file_extension="${1##*.}"
		        case "$file_extension" in
		            h|hpp|hxx)
				                return 0
						            ;;
			            *)
					                return 1
							            ;;
				        esac
}

# Change mode for all files except README.md
for file in *
do
    if [[ "$file" != "README.md" ]]
        then
	        chmod a+x "$file"
		    fi
		    done

# Git add and commit for README.md and header files
		    commit_message="Added dependency files README.md"
		    header_files=""
		    for file in README.md *
		    do
		        if [[ "$file" != "README.md" && -f "$file" && $(is_header_file "$file") -eq 0 ]]
			    then
			            git add "$file"
				            commit_message+=" and $file"
					            header_files+=" $file"
						        fi
							done

							git commit -m "$commit_message"

# Git push
							git push

# Git add and commit for remaining files
							read -p "Do you want to add all remaining files? (Y/n): " add_all_files
							if [[ "$add_all_files" == "Y" || "$add_all_files" == "y" ]]
							then
							    git add .
							    else
							        read -p "Enter file names separated by space: " custom_files
								    git add $custom_files
								    fi

								    current_folder=$(basename "$(pwd)")
								    git commit -m "Solved all tasks on project $current_folder"

# Git push
								    git push

